# Generated by Django 5.0.1 on 2024-01-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reporting_manager',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
